services:
  embedding:
    image: cppd86/embed_service:latest
    container_name: embedding_service
    ports:
      - "8000:8000"
    networks:
      - rag-network

  ragapp:
    image: cppd86/rag_service:latest
    container_name: rag_app
    ports:
      - "7000:7000"
    networks:
      - rag-network
    depends_on:
      - embedding

networks:
  rag-network:
    driver: bridge