version: "3.9"

services:
  embedding:
    image: embeder_service:latest
    container_name: embedding_service
    ports:
      - "8000:8000"   # optional, only if you want to access from host
    networks:
      - rag-network

  ragapp:
    image: rag_service:latest
    container_name: rag_app
    ports:
      - "7000:7000"   # optional, for accessing RAG app from host
    networks:
      - rag-network
    depends_on:
      - embedding

networks:
  rag-network:
    driver: bridge
